name: examples
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15
      - run: pnpm install --filter with-angular
      - name: Integration tests
        run: pnpm test:integration
        working-directory: ./examples/with-angular
      - name: E2E tests
        run: pnpm test:e2e
        working-directory: ./examples/with-angular

  remix:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15
      - run: pnpm install --filter with-remix
      - name: E2E tests
        run: pnpm test:e2e
        working-directory: ./examples/with-remix

  svelte:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15
      - run: pnpm install --filter with-svelte
      - name: E2E tests
        run: pnpm test:e2e
        working-directory: ./examples/with-svelte

  vue:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15
      - run: pnpm install --filter with-vue
      - name: Integration tests
        run: pnpm test:integration
        working-directory: ./examples/with-vue
      - name: E2E tests
        run: pnpm test:e2e
        working-directory: ./examples/with-vue

  jest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15
      - run: pnpm install --filter with-jest
      - run: pnpm test --filter with-jest

  jest-jsdom:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15
      - run: pnpm install --filter with-jest-jsdom
      - run: pnpm test --filter with-jest-jsdom

  vitest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15
      - run: pnpm install --filter with-vitest
      - run: pnpm test --filter with-vitest

  vitest-cjs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15
      - run: pnpm install --filter with-vitest-cjs
      - run: pnpm test --filter with-vitest-cjs

  playwright:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15
      - run: pnpm install --filter with-playwright
      - run: pnpm test --filter with-playwright

  karma:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15
      - run: pnpm install --filter with-karma
      - run: pnpm test --filter with-karma
